// Auto-generated API functions for fileuploader plugin
// Generated by refresh_frontend_apis.py
// Do not edit this file manually - it will be overwritten

const API_URL = window._env_?.VITE_API_URL || "http://localhost:8000";

/**
 * Fileuploader Plugin API Functions
 * Auto-generated from backend implementation
 */

/**
 * Get File Uploader information
 */
export const fileuploaderInfo = async () => {
  try {
    const url = `${API_URL}/fileuploader/`
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling fileuploaderInfo:', error);
    throw error;
  }
};


// Default export with all functions
export default {
fileuploaderInfo
};
